# opencode.sh — sourced by maude-bootstrap.sh and the maude CLI.
# Installs/updates OpenCode (opencode.ai — open-source terminal agent, used in
# Maude to drive open-weight LLMs such as GLM), refreshes the bundled
# `opencode` skill into ~/.claude/skills/opencode, and generates
# ~/.config/opencode/opencode.json with all providers pre-declared.
#
# Depends on llm-mode.sh (detect_llm_mode, maude_fetch_skill).

: "${MAUDE_RAW:=https://raw.githubusercontent.com/dirkpetersen/maude/main/light}"

update_opencode() {
    local rc=0
    local cli_status="unchanged" skill_status="unchanged" config_status="kept (user-owned)"

    # ── OpenCode CLI (installed globally via Bun, like gemini/kanna) ──
    # npm package is 'opencode-ai', NOT 'opencode'. The curl installer would
    # append its own PATH lines to ~/.bashrc, which Maude manages itself.
    if command -v bun >/dev/null 2>&1; then
        # Resolve the binary by path, not bare name — the caller's PATH may
        # not include ~/.bun/bin or a freshly-created ~/.local/bin yet.
        # bun installs globals under BUN_INSTALL when set, so honour it.
        local oc_bin="${BUN_INSTALL:-$HOME/.bun}/bin/opencode"
        local ver_before ver_after
        ver_before=$([[ -x "$oc_bin" ]] && "$oc_bin" --version 2>/dev/null | grep -oP '[\d.]+' | head -1)
        if bun install -g opencode-ai >/dev/null 2>&1; then
            if [[ -x "$oc_bin" ]]; then
                mkdir -p "$HOME/.local/bin"
                ln -sfn "$oc_bin" "$HOME/.local/bin/opencode"
                ver_after=$("$oc_bin" --version 2>/dev/null | grep -oP '[\d.]+' | head -1)
                if [[ -n "$ver_after" && -z "$ver_before" ]]; then
                    cli_status="installed (v${ver_after})"
                elif [[ -n "$ver_after" && "$ver_before" != "$ver_after" ]]; then
                    cli_status="updated (${ver_before} → ${ver_after})"
                else
                    cli_status="up to date${ver_after:+ (v${ver_after})}"
                fi
            else
                # bun exited 0 but the binary isn't there — do NOT report
                # success; a silent "up to date" here hides a broken install.
                cli_status="failed (bun install ok but $oc_bin missing)"
                rc=1
            fi
        else
            cli_status="failed"
            rc=1
        fi
    else
        cli_status="skipped (bun not found)"
        rc=1
    fi

    # ── OpenCode skill ──
    if declare -F maude_fetch_skill >/dev/null; then
        if skill_status=$(maude_fetch_skill opencode); then :; else rc=1; fi
    else
        skill_status="skipped (llm-mode.sh not loaded)"
        rc=1
    fi

    # ── ~/.config/opencode/opencode.json — only when absent or maude-managed ──
    # {env:VAR} placeholders are expanded by opencode at runtime, so no key
    # material is ever written here. GLM is not reachable through Azure
    # (Fireworks-on-Foundry only), so azure mode keeps the direct Z.ai default.
    local cfg="$HOME/.config/opencode/opencode.json"
    if [[ ! -f "$cfg" ]] || grep -q 'managed by maude' "$cfg" 2>/dev/null; then
        mkdir -p "$(dirname "$cfg")"
        local was_new="rewritten"
        [[ -f "$cfg" ]] || was_new="written (new)"
        local mode; mode=$(detect_llm_mode 2>/dev/null || echo direct)
        local oc_model
        case "$mode" in
            aws) oc_model="amazon-bedrock/zai.glm-5" ;;
            *)   oc_model="zai-coding-plan/glm-5.2" ;;
        esac
        cat > "$cfg" <<EOF
{
  "\$schema": "https://opencode.ai/config.json",
  "//": "managed by maude — regenerated by 'maude update' while this key is present; remove it to take ownership",
  "model": "${oc_model}",
  "provider": {
    "zai-coding-plan": { "options": { "apiKey": "{env:ZHIPU_API_KEY}" } },
    "amazon-bedrock":  { "options": { "region": "{env:AWS_REGION}" } },
    "azure":           { "options": { "apiKey": "{env:AZURE_API_KEY}" } }
  }
}
EOF
        config_status="$was_new (default: ${oc_model})"
    fi

    # Print status lines for the caller (update_all reads them).
    printf '%s\n' "cli:$cli_status" "skill:$skill_status" "config:$config_status"
    return $rc
}
